import MCP

extension Server {
  /// Registers the provided prompts with the MCP server using the recommended handlers.
  ///
  /// The server automatically responds to `prompts/list` with metadata generated by each
  /// prompt's `toPrompt()` output and wires `prompts/get` to the prompt's `getMessages`
  /// method.
  ///
  /// ## Example
  ///
  /// ```swift
  /// let server = Server(
  ///   name: "Prompt Server",
  ///   version: "1.0.0",
  ///   capabilities: .init(prompts: .init(listChanged: true))
  /// )
  ///
  /// await server.register(prompts: [
  ///   GreetingPrompt(),
  ///   CodeReviewPrompt()
  /// ])
  /// ```
  ///
  /// - Parameter prompts: The collection of prompts that should be surfaced to MCP clients.
  /// - SeeAlso: https://modelcontextprotocol.io/specification/2025-06-18/server/prompts
  public func register(prompts: [any MCPPrompt]) async {
    self.withMethodHandler(ListPrompts.self) { _ in
      .init(prompts: prompts.map { $0.toPrompt() }, nextCursor: nil)
    }

    self.withMethodHandler(GetPrompt.self) { params async throws in
      guard let prompt = prompts.first(where: { $0.name == params.name }) else {
        throw MCPError.invalidParams("Unknown prompt: \(params.name)")
      }

      return try await prompt.callGetMessages(with: params.arguments)
    }
  }
}
